[Variables]
Data =<sun rise="2014-08-19T06:00:03" set="2014-08-19T18:06:59"/>
  </city>
  <temperature value="22.878" min="22.878" max="22.878" unit="celsius"/>
  <humidity value="100" unit="%"/>
  <pressure value="1026.41" unit="hPa"/>
  <wind>
    <speed value="2.46" name="Light breeze"/>
    <direction value="164.501" code="SSE" name="South-southeast"/>
  </wind>
  <clouds value="12" name="few clouds"/>
  <visibility/>
  <precipitation mode="no"/>
  <weather number="801" value="few clouds" icon="02n"/>
